---
# Destroy pools created in Lab 4

- name: "Delete UUID Pool Details"
  vars:
    api_info: &api_info_uuid
      api_private_key: "{{ intersight_api_private_key }}"
      api_key_id: "{{ intersight_api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"

  cisco.intersight.intersight_rest_api:
      <<: *api_info_uuid
      resource_path: /uuidpool/Pools
      query_params:
         $filter: "Name eq '{{ name_of_uuid_pool }}'"

- name: "Delete IP Address Pool Details"
  vars:
    api_info: &api_info_ip_pool
      api_private_key: "{{ intersight_api_private_key }}"
      api_key_id: "{{ intersight_api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"
  block:
    - name: Delete IB-MGMT IP Pool
      cisco.intersight.intersight_rest_api:
        <<: *api_info_ip_pool
        resource_path: /ippool/Pools
        query_params:
          $filter: "Name eq '{{ name_of_ip_pool_for_ib_management_access }}'"

    - name: Delete OOB-MGMT IP Pool
      cisco.intersight.intersight_rest_api:
        <<: *api_info_ip_pool
        resource_path: /ippool/Pools
        query_params:
          $filter: "Name eq '{{ name_of_ip_pool_for_oob_management_access }}'"


- name: "Delete MAC Address Pool for FI-A"
  vars:
    api_info: &api_info_mac_a_pool
      api_private_key: "{{ intersight_api_private_key }}"
      api_key_id: "{{ intersight_api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"

  cisco.intersight.intersight_rest_api:
    <<: *api_info_mac_a_pool
    resource_path: /macpool/Pools
    query_params:
      $filter: "Name eq '{{ name_of_mac_pool_on_fi_a }}'"


- name: "Delete MAC Address Pool for FI-B"
  vars:
    api_info: &api_info_mac_b_pool
      api_private_key: "{{ intersight_api_private_key }}"
      api_key_id: "{{ intersight_api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"

  cisco.intersight.intersight_rest_api:
    <<: *api_info_mac_b_pool
    resource_path: /macpool/Pools
    query_params:
      $filter: "Name eq '{{ name_of_mac_pool_on_fi_b }}'"

- name: "Delete WWNN Pool Details"
  vars:
    api_info: &api_info_wwnn_pool
      api_private_key: "{{ intersight_api_private_key }}"
      api_key_id: "{{ intersight_api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"

  cisco.intersight.intersight_rest_api:
    <<: *api_info_wwnn_pool
    resource_path: /fcpool/Pools
    query_params:
      $filter: "Name eq '{{ name_of_wwnn_pool }}'"
  when: configure_fc == 'true'

- name: "Delete WWPN Pool Details of SAN-A"
  vars:
    api_info: &api_info_wwpn_a_pool
      api_private_key: "{{ intersight_api_private_key }}"
      api_key_id: "{{ intersight_api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"

  cisco.intersight.intersight_rest_api:
    <<: *api_info_wwpn_a_pool
    resource_path: /fcpool/Pools
    query_params:
      $filter: "Name eq '{{ name_of_wwpn_pool_san_a }}'"
  when: configure_fc == 'true'

- name: "Delete WWPN Pool Details of SAN-B"
  vars:
    api_info: &api_info_wwpn_b_pool
      api_private_key: "{{ intersight_api_private_key }}"
      api_key_id: "{{ intersight_api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"

  cisco.intersight.intersight_rest_api:
    <<: *api_info_wwpn_b_pool
    resource_path: /fcpool/Pools
    query_params:
      $filter: "Name eq '{{ name_of_wwpn_pool_san_b }}'"
  when: configure_fc == 'true'

- name: "Delete IQN Pool"
  vars:
    api_info: &api_info_iqn
      api_private_key: "{{ intersight_api_private_key }}"
      api_key_id: "{{ intersight_api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"

  cisco.intersight.intersight_rest_api:
      <<: *api_info_iqn
      resource_path: /iqnpool/Pools
      query_params:
         $filter: "Name eq '{{ name_of_iqn_pool }}'"
  when: configure_iscsi == 'true'

-  name: "Delete IP Pool for iSCSI-A"
   vars:
     api_info: &api_info_iscsi_a
       api_private_key: "{{ intersight_api_private_key }}"
       api_key_id: "{{ intersight_api_key_id }}"
       api_uri: "{{ api_uri | default(omit) }}"
       validate_certs: "{{ validate_certs | default(omit) }}"
       state: "{{ state | default(omit) }}"

   cisco.intersight.intersight_rest_api:
        <<: *api_info_iscsi_a
        resource_path: /ippool/Pools
        query_params:
           $filter: "Name eq '{{ name_of_ip_pool_for_iscsi_a }}'"
   when: configure_iscsi == 'true'


-  name: "Delete IP Pool for iSCSI-B"
   vars:
     api_info: &api_info_iscsi_b
       api_private_key: "{{ intersight_api_private_key }}"
       api_key_id: "{{ intersight_api_key_id }}"
       api_uri: "{{ api_uri | default(omit) }}"
       validate_certs: "{{ validate_certs | default(omit) }}"
       state: "{{ state | default(omit) }}"
       
   cisco.intersight.intersight_rest_api:
        <<: *api_info_iscsi_b
        resource_path: /ippool/Pools
        query_params:
           $filter: "Name eq '{{ name_of_ip_pool_for_iscsi_b }}'"
   when: configure_iscsi == 'true'
