---
- name: LAB5 Derive Profiles
  hosts: serverprofile_esx
  connection: local
  gather_facts: false
  vars:
    intersight_api_login_info: &intersight_api_login_info
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ intersight_validate_certs | default(omit) }}"
  tasks:
    - name: Query for an existing Organization and return Moid
      cisco.intersight.intersight_rest_api:
        <<: *intersight_api_login_info
        resource_path: /organization/Organizations
        query_params:
          $filter: "Name eq '{{ organization_name }}'"
      register: organization_response
      run_once: true

    - name: Moid for Organization
      ansible.builtin.set_fact:
        organization_moid: "{{ organization_response.api_response.Moid }}"
      run_once: true
      delegate_to: local_host

    - name: Get MOID of SPTemplate
      cisco.intersight.intersight_rest_api:
        <<: *intersight_api_login_info
        resource_path: /server/ProfileTemplates
        query_params:
          $filter: "Name eq '{{ SPTemplate }}'"
      register: sptemplate_answer
      run_once: true

    - name: Moid for sptemplate
      ansible.builtin.set_fact:
        sptemplate_moid: "{{ sptemplate_answer.api_response.Moid }}"
      run_once: true
      delegate_to: local_host

    - name: Call MoCloner to Derive Profile
      cisco.intersight.intersight_rest_api:
        <<: *intersight_api_login_info
        resource_path: /bulk/MoCloners
        query_params:
          $filter: "Name eq '{{ inventory_hostname }}'"
        api_body: {
          "Sources": [
              {
                  "Moid": "{{sptemplate_moid}}",
                  "ObjectType": "server.ProfileTemplate"
              }
          ],
          "Targets": [
              {
                  "Description": "{{ inventory_hostname }} server profile derived from {{ SPTemplate }}",
                  "Name": "{{ inventory_hostname }}",
                  "ObjectType": "server.Profile",
                  "Organization": {
                      "Moid": "{{ organization_moid }}",
                  },
                  "Tags": [
                    {"Key": "Provisioned by:", "Value": "Intersight-Ansible"},
                    {"Key": "Project:", "Value": "Workshop-{{ group_prefix }}"}
                    ],           
              }
            ]
        }