---
- name: LAB3 Create NTP Policy via REST
  hosts: localhost
  gather_facts: false
  vars:
    intersight_api_login_info: &intersight_api_login_info
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ intersight_validate_certs | default(omit) }}"
  tasks:
    - name: Query for an existing Organization and return Moid
      cisco.intersight.intersight_rest_api:
        <<: *intersight_api_login_info
        resource_path: /organization/Organizations
        query_params:
          $filter: "Name eq '{{ organization_name }}'"
      register: organization_response
      run_once: true

    - name: Moid for Organization
      ansible.builtin.set_fact:
        organization_moid: "{{ organization_response.api_response.Moid }}"
      run_once: true
      delegate_to: local_host
      
    - name: Print status of 'Query Organization' policy
      ansible.builtin.debug:
        msg: "Queried Organization '{{ organization_name }}' with Moid: '{{ organization_moid }}'"

    - name: Configure NTP Policy
      cisco.intersight.intersight_rest_api:
        <<: *intersight_api_login_info
        resource_path: /ntp/Policies
        query_params:
          $filter: "Name eq '{{ ntp_policy_name }}'"
        api_body: {
          "AuthenticatedNtpServers": [],
          "ClassId": "ntp.Policy",
          "Description": "{{ ntp_policy_description }}",
          "Enabled": true,
          "Name": "{{ ntp_policy_name }}",
          "NtpServers": "{{ ntp_policy_srv_lst }}",
          "ObjectType": "ntp.Policy",
          "Organization": {
            "Moid": "{{ organization_moid }}"
            },
          "Profiles": [],
          "Tags": [
            {"Key": "Provisioned by:", "Value": "Intersight-Ansible"},
            {"Key": "Project:", "Value": "Workshop-{{ group_prefix }}"}
            ],
          "Timezone": "Europe/Zurich"
        } 
        state: present